Hive sprint 6 demande d amis
hivolunteer/web pull request #113
Opened 2024-11-12 14:29 UTC by Petroflo

Nouvelle version de la page avec le bon filtrage

2024-11-23 11:33 UTC, Bill-ON-epitech commented on src/pages/Volunteer/Amis/FriendRequestCard.tsx
> +            body: JSON.stringify({ id: localStorage.getItem("id") })
pourquoi ne pas utilise volunteer.id dans les 2 cas ?

2024-11-23 11:37 UTC, Bill-ON-epitech reviewed
je crois qu'on voulait supprimer l'id de localStorage (PAS bloquant)
mais sinon tout va bien

2024-11-23 23:34 UTC, tdcastillon requested changes
Hormis l'ID a supprimé, le code semble correct. Si possible corrige ça. (Je testerai la version front aprés)

2024-11-23 23:34 UTC, tdcastillon commented on src/pages/Volunteer/Amis/FriendRequestCard.tsx
> +            body: JSON.stringify({ id: localStorage.getItem("id") })
Si le token est envoyé, cet  envoi d'ID est inutile

2024-12-04 08:52 UTC, Petroflo commented
> Hormis l'ID a supprimé, le code semble correct. Si possible corrige ça. (Je testerai la version front aprés)

Je retire l'id complètement ou je mets localstorage comme Bill a suggéré? @tdcastillon

2024-12-04 23:16 UTC, tdcastillon requested changes

2024-12-04 23:16 UTC, tdcastillon commented on src/pages/Volunteer/Amis/FriendRequestCard.tsx
> +            body: JSON.stringify({ id: localStorage.getItem("id") })
ici @Petroflo faut pas envoyer de body

2024-12-05 10:42 UTC, louis-henrieu approved these changes
OK

2024-12-05 10:47 UTC, louis-henrieu requested changes
Dans ton dernier commit tu as corrigé des utilisations de l'id dans le body mais pas celui à la ligne 23 du fichier FriendRequestCard
cf conversation Discord dans APT APT

2024-12-05 11:02 UTC, Petroflo commented
> Dans ton dernier commit tu as corrigé des utilisations de l'id dans le body mais pas celui à la ligne 23 du fichier FriendRequestCard cf conversation Discord dans APT APT

C'est vrai, j'en ai loupé un, c'est repush

2024-12-05 14:48 UTC, tdcastillon approved these changes
Test in vocal channel with Petro

2024-12-05 21:28 UTC, merged